sonar.projectKey=VED-VirtualExperienceDevelopment_bistrolink
sonar.organization=ved-virtualexperiencedevelopment
sonar.sources=apps/backend/src,apps/frontend/src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.ts,**/coverage/**,**/.next/**
sonar.javascript.lcov.reportPaths=apps/backend/coverage/lcov.info,apps/frontend/coverage/lcov.info
