sonar.projectKey=VED-VirtualExperienceDevelopment_bistrolink
sonar.organization=ved-virtualexperiencedevelopment
sonar.sources=apps/backend/src,apps/frontend/src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.ts,**/coverage/**,**/.next/**
sonar.coverage.exclusions=**/*
